### ISSUE TITLE
Requirements obsolètes

### ISSUE THREAD

**Issue by josephbedminster** [massard-t/etna-stud#2]
Hi Theo,

When I tried to build the Docker container, i had the following result : 
`Collecting etnawrapper==0.5 (from -r requirements.txt (line 2))
  Could not find a version that satisfies the requirement etnawrapper==0.5 (from -r requirements.txt (line 2)) (from versions: 1.0)
No matching distribution found for etnawrapper==0.5 (from -r requirements.txt (line 2))
The command '/bin/sh -c pip install --no-cache-dir -r requirements.txt' returned a non-zero code: 1`

Please update file requirements.txt, line 2 : 
`etnawrapper==0.5`
to
`etnawrapper==1`

Thanks for your work,
Joseph

**Comment by tbobm** [comment]
Thanks for pointing it out Joseph!
